version: "3"

networks:
  gitea:
    external: false

volumes:
  postgres-s3:
    driver: local
  gitea-s3:
    driver: local

services:
  server:
    image: gitea/gitea:1.17.1
    container_name: gitea
    environment:
      - name
    env_file:
      - stack.env
    restart: always
    networks:
      - gitea
    volumes:
      - gitea-s3:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:3000"
      - "2221:22"
    depends_on:
       - db
  db:
    image: postgres:14
    restart: always
    env_file:
      - stack.env
    networks:
      - gitea
    volumes:
      - postgres-s3:/var/lib/postgresql/data
